//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrewdayFermentationProfile
    {
        public int id { get; set; }
        public Nullable<int> brewdayId { get; set; }
        public Nullable<int> primaryDays { get; set; }
        public Nullable<double> primaryTemp { get; set; }
        public string primaryNote { get; set; }
        public Nullable<int> secondaryDays { get; set; }
        public Nullable<double> secondaryTemp { get; set; }
        public string secondaryNote { get; set; }
        public Nullable<int> kegDays { get; set; }
        public Nullable<double> kegTemp { get; set; }
        public string kegNote { get; set; }
        public Nullable<int> bottleDays { get; set; }
        public Nullable<double> bottleTemp { get; set; }
        public string bottleNote { get; set; }
    }
}
