//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BrewdayFermentable
    {
        public int id { get; set; }
        public Nullable<int> recipeId { get; set; }
        public Nullable<int> ingredientId { get; set; }
        public Nullable<bool> isMashed { get; set; }
        public string url { get; set; }
        public Nullable<double> amount { get; set; }
        public string unit { get; set; }
    }
}
