//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EquipmentProfile
    {
        public int id { get; set; }
        public string authorId { get; set; }
        public string name { get; set; }
        public Nullable<double> kettleVolume { get; set; }
        public Nullable<double> kettleBoiloff { get; set; }
        public Nullable<double> kettleVolumeLoss { get; set; }
        public Nullable<double> mashtunVolume { get; set; }
        public Nullable<double> mashtunVolumeLoss { get; set; }
        public Nullable<double> mashEfficiency { get; set; }
    }
}
