//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hop
    {
        public int id { get; set; }
        public string name { get; set; }
        public double alphaAcid { get; set; }
        public Nullable<double> amount { get; set; }
        public string unit { get; set; }
        public Nullable<int> additionTime { get; set; }
        public Nullable<bool> isLeaf { get; set; }
    }
}
