//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MashEntry
    {
        public int id { get; set; }
        public Nullable<int> recipeId { get; set; }
        public Nullable<int> time { get; set; }
        public Nullable<double> temperature { get; set; }
        public string method { get; set; }
        public string mashSpargeType { get; set; }
    }
}
