//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRMtoRGB
    {
        public double SRM { get; set; }
        public Nullable<int> Red { get; set; }
        public Nullable<int> Green { get; set; }
        public Nullable<int> Blue { get; set; }
    }
}
