//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrewingSite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Style
    {
        public int id { get; set; }
        public string Style1 { get; set; }
        public string Low_OG { get; set; }
        public string Hi_OG { get; set; }
        public string Low_FG { get; set; }
        public string Low_ABV { get; set; }
        public string Low_IBU { get; set; }
        public string Low_SRM { get; set; }
        public string Hi_SRM { get; set; }
        public string CO2_Vols { get; set; }
        public string Hi_FG { get; set; }
        public string Hi_ABV { get; set; }
        public string Hi_IBU { get; set; }
    }
}
